baseURL = "https://mazza.com.ar/"
languageCode = "es"
title = "Mazza"
theme = "mazza"
pluralizelisttitles = "false"
sectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true